### ISSUE TITLE
Translation for the newly integrated publish filtering

### ISSUE THREAD

**Issue by animaux** [hananils/lang_german#5]
Are all the strings in the interface translatable?

**Comment by nilshoerrmann** [comment]
They should be. Anything missing?

**Comment by animaux** [comment]
![bildschirmfoto 2015-01-08 um 10 48 24](https://cloud.githubusercontent.com/assets/446874/5660725/ea459d50-9723-11e4-9176-abeabf8a29fa.png)

Ein Bild sagt mehr als 1000 …

**Comment by nilshoerrmann** [comment]
Ja, aber das sagt ja erstmal nur, dass die Texte nicht übersetzt sind. Nicht, dass sie nicht übersetzbar wären. :)

**Comment by animaux** [comment]
50% Success!

**Comment by nilshoerrmann** [comment]
Die Übersetzung sollte jetzt komplett sein.
Sie sie doch grundsätzlich einmal durch und schicke gegebenenfalls Korrekturen. Danke!

**Comment by animaux** [comment]
Danke! »Apply filters« und »Clear filters« seh’ ich auf Anhieb noch. Sonst tipptop :)

**Comment by nilshoerrmann** [comment]
Hast Du den neusten `integration`-Code?

**Comment by animaux** [comment]
Von Symphony? \*checking out\*

**Comment by animaux** [comment]
:heavy_check_mark:

**Comment by nilshoerrmann** [comment]
Prima :)

**Comment by nilshoerrmann** [comment]
Ich bin jetzt gerade den Core noch mal nach fehlenden Übersetzungenmöglichkeiten durchgegangen. Wenn Du sowohl Symphony als auch diese Übersetzung aktualisierst, sollte noch ein bisschen was dazugekommen sein.

**Comment by animaux** [comment]
Prima, danke!

**Comment by animaux** [comment]
Hmm, sind Deine Änderungen in Symphony schon in der `integration`-branch? Die ist 6 Tage alt, Dein Kommentar aber 4.

**Comment by nilshoerrmann** [comment]
Ja, die Commits vom 8. Januar hier: https://github.com/symphonycms/symphony-2/commits/integration

**Comment by animaux** [comment]
Komisch, mein Github for Mac listet die nicht auf. :|

**Comment by nilshoerrmann** [comment]
Aber online siehst Du sie?

**Comment by animaux** [comment]
Yip, löschen und neu reinladen in Github for Mac hat das Problem gelöst …

**Comment by nilshoerrmann** [comment]
Prima.

**Comment by animaux** [comment]
Übersetzung ist nun auch prima :) danke!

**Comment by nilshoerrmann** [comment]
Hab mal ein Auge auf Flüchtigkeitsfehler – ich habe ansonsten bisher auch nicht überprüft, ob die Übersetzung insgesamt stimmig ist, also gleichartige Formulierung auch gleichartig übersetzt sind.

**Comment by animaux** [comment]
Ok. Bisher sieht alles gut aus soweit.
